### ISSUE TITLE
Strings don't wrap 

### ISSUE THREAD

**Issue by B-Souty** [lineaba/prog-o-meter#44]
Because the strings don't wrap, I am sometime missing part of a text (c.f. screenshot)

![screenshot_20180422_182910](https://user-images.githubusercontent.com/37458498/39097361-7e4b6248-465b-11e8-9f27-9241206d803a.png)

I was able to fix the issue by changing line 233:

`self.canvas.create_text(self.CANVAS_WIDTH/2,` 20, text = "Good to see you again! Please enter your name")`

to something like this.      

`self.canvas.create_text(self.CANVAS_WIDTH/2, 20, width = self.CANVAS_WIDTH-20, text = "Good to see you again! Please enter your name")`

Let me know if you like this fix and I'll apply it to all the strings that might be impacted by this issue.

**Comment by lineaba** [comment]
Hey, interesting problem. I am glad the program is being tested out on multiple machines and operating systems.
I am worried your solution it might cause problems in cases where there are two lines of text right below each other, since the wrap of the first line could end up overlapping with the position of the second line. 
I am wondering if we would possibly solve the problem by setting the font. Tkinter font default is system specific (http://effbot.org/tkinterbook/canvas.htm#Tkinter.Canvas.create_text-method), so I assume my system's default font fits within the size of the window, while yours doesn't. 
On this [link](http://effbot.org/tkinterbook/tkinter-widget-styling.htm), under font descriptors, they explain how to specify size and font-type for text in Tkinter.
Will you maybe try and see if changing the font from default to some specific font, can fix the problem, and keep all the text within the window on your machine?
If that works, I would suggest we solve the problem that way. This would also mean that the prog-o-meter interface looks more similar to all users. 
Let me know what you think, or if someone has other suggestions for solution.

**Comment by B-Souty** [comment]
if you declare all your lines within the same canvas using `\n` for new line and the `justify` parameters I reckon you should be able to avoid overlapping. 

However, as you mentioned, considering that tkinter is using the system default font, other issues might arise going forward. Hardcoding the font-type and its size might be the best solution. But then that would mean finding a font that would work across all platform or adding a switch statement to take into account the OS.

**Comment by lineaba** [comment]
Hmm, yeah, this problem is a bit of a headscratcher.

I like the simplicity of using \n and justify, but I wonder if we could encounter problems given the small size of some of the the windows. Could we risk a system's default font takes up so much space, that we risk the text falling of the bottom of the widget due to too many lines, by taking this approach?

I have been looking a bit into hard-coding a font-type and size. Tkinter has a TkFixedFont, which is a monospace font (and will use a font from the specific platform that fulfills the width requirements).
This means that it should work across platforms, and that width will be consistent, while the exact look might differ. It should solve the width problem, although we would have to increase size of the windows, as this font is wider than the font used while I chose the size of the windows.
The look of these mono width fonts is not my personal favorite, so I am very curious to see what other solutions we might have?

**Comment by lineaba** [comment]
Here is a link about font and Tkinter http://www.tkdocs.com/tutorial/fonts.html

**Comment by lineaba** [comment]
@B-Souty Do you wanna have a go at solving this problem?

**Comment by B-Souty** [comment]
@lineaba It seems like everyday the look of the prog-o-meter changes on my computer because I keep playing around with the settings. Unless we get other people complaining about this,  I don't think we should waste time on this.

Plus, lately the fonts size seems to have reduce somehow and it now fits fine in the window. If nobody else complain about this by monday, I'll close the issue. How does that sound?

**Comment by lineaba** [comment]
Yeah, that sounds good!
